# Generated by Django 3.2.3 on 2021-05-22 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=200)),
                ('website', models.CharField(max_length=100)),
                ('tokped', models.CharField(max_length=100)),
                ('shopee', models.CharField(max_length=100)),
                ('ig', models.CharField(max_length=100)),
            ],
        ),
    ]
