# Generated by Django 3.2.3 on 2021-05-22 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project2', '0002_alter_brand_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='brand',
            table='Tabel Brand',
        ),
    ]
