# Generated by Django 3.2.3 on 2021-05-22 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project2', '0003_alter_brand_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='ig',
            field=models.CharField(default='-', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='shopee',
            field=models.CharField(default='-', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='tokped',
            field=models.CharField(default='-', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='website',
            field=models.CharField(default='-', max_length=100, null=True),
        ),
    ]
