# Generated by Django 3.2.3 on 2021-05-22 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project2', '0004_auto_20210522_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_pakaian', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Type Pakaian',
            },
        ),
    ]
