# Generated by Django 3.2.3 on 2021-05-22 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project2', '0006_auto_20210522_1257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name_plural': 'Tabel Brand'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name_plural': 'Tipe Pakaian'},
        ),
    ]
