# Generated by Django 3.2.3 on 2021-05-22 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project2', '0007_auto_20210522_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='image_product/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name_plural': 'Brand'},
        ),
    ]
