# Generated by Django 3.2.3 on 2021-05-22 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project2', '0008_auto_20210522_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('type_pakaian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project2.type')),
            ],
            options={
                'verbose_name': 'Product',
            },
        ),
    ]
